version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Test
          command: |
            pwd 
            ls -la
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
workflows:
  Build: 
    jobs:
      - build-and-test
