version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Test
          command: |
            cat /etc/os-release
            pwd 
            ls -la
            mvn -v
      - run:
          name: Build
          command: |
            mvn -B -DskipTests clean package
            mvn install
            ls -la
            cd target
            chmod 777 jiracon22.war
            ls -la
      - run:
          name: Test Cases
          command: mvn test
      - run:
          name: Tomcat Install
          command: |
            sudo useradd -m -d /opt/tomcat -U -s /bin/false tomcat
            sudo apt update
            sudo apt install default-jdk
            java -version
            cd /tmp
            wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
            sudo tar xzvf apache-tomcat-10*tar.gz -C /opt/tomcat --strip-components=1
            sudo chown -R tomcat:tomcat /opt/tomcat/
            sudo chmod -R u+x /opt/tomcat/bin
            sudo systemctl daemon-reload
            sudo systemctl start tomcat
            sudo systemctl status tomcat
            sudo systemctl enable tomcat
            sudo ufw allow 8080
          
workflows:
  Build: 
    jobs:
      - build
