version: 2.1
orbs:
    jira: circleci/jira@2.1.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Test
          command: |
            cat /etc/os-release
            mv /home/circleci/project/circleci.pem /home/circleci/
            chmod 777 /home/circleci/circleci.pem
            pwd 
            ls -la
            mvn -v
      - run:
          name: Build
          command: |
            mvn -B -DskipTests clean install
            ls -la
            cd target
            chmod 777 jiracon22-1.0.0.war
            pwd
            ls -la
      - run:
          name: Test Cases
          command: |
            mvn test
      - add_ssh_keys:
          fingerprints:
            - "cf:a2:ff:95:50:ae:02:00:56:95:f5:bb:93:3f:c3:56"
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /tmp/artifacts;
            cd /home/circleci/project/target
            cp -r jiracon22-1.0.0.war /tmp/artifacts
            cd /tmp
            ls -la
            cd /tmp/artifacts/
            ls -la
      
      - store_artifacts:
            path: /tmp/artifacts
      - run:
          name: Set Artifact Link Environment Variable
          command: |
            # Specify the known location and filename of the artifact
            ARTIFACT_LOCATION="/tmp/artifacts/jiracon22-1.0.0.war"
            # Create or update the environment file with the artifact link
            echo "ARTIFACT_LINK=${ARTIFACT_LOCATION}" > /tmp/artifacts/$BASH_ENV_FILENAME
            ls -l /tmp/artifacts
          shell: bash
      - run:
          name: Update Jira with Artifact Link
          command: |
            pwd 
            ls -la
            chmod 777 ./update_jira.sh
            ./update_jira.sh
      - store_artifacts:
            path: /tmp/artifacts
      - run:
          name: Update Jira with Artifact Link
          command: |
            cd /tmp/artifacts
            ls -la

  deploy:
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            # Replace 'YOUR_EC2_INSTANCE_IP' and '/path/on/ec2/server' with actual values
            cat /etc/os-release
            mvn -B -DskipTests clean install
            ls -la
            cd target
            chmod 777 jiracon22-1.0.0.war
            pwd
            ls -la
            mv /home/circleci/project/circleci.pem /home/circleci/
            chmod 777 /home/circleci/circleci.pem
            sudo scp -o StrictHostKeyChecking=no -i /home/circleci/circleci.pem /home/circleci/project/target/jiracon22-1.0.0.war ec2-user@34.207.198.25:/opt/apache-tomcat-9.0.81/webapps/jiracon22-1.0.0.war
      - jira/notify:
          environment: staging
          environment_type: staging
          job_type: deployment
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >> 

workflows:
  build and deploy: 
    jobs:
      - build:
          context: Jira
      - deploy: 
          requires:
            - build
          context: Jira
