<head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Your work - Bitbucket</title><script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.bitbucket.server.config-wrm-data:dashboard.poll.jira-issues.interval.data"]="{\u0022value\u0022:\u002230000\u0022,\u0022key\u0022:\u0022dashboard.poll.jira-issues.interval\u0022,\u0022type\u0022:\u0022NUMBER\u0022}";
WRM._unparsedData["com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:user-keyboard-shortcuts-enabled.data"]="true";
WRM._unparsedData["com.atlassian.analytics.analytics-client:programmatic-analytics-init.programmatic-analytics-data-provider"]="false";
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\u0022\u0022";
WRM._unparsedData["com.atlassian.plugins.atlassian-clientside-extensions-runtime:runtime.atlassianDevMode"]="false";
WRM._unparsedData["com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:date-format-preference.data"]="\u0022ABSOLUTE\u0022";
WRM._unparsedData["com.atlassian.bitbucket.server.feature-wrm-data:bitbucket.global.theme.data"]="false";
WRM._unparsedData["com.atlassian.analytics.analytics-client:policy-update-init.policy-update-data-provider"]="false";
WRM._unparsedData["com.atlassian.bitbucket.server.config-wrm-data:dashboard.poll.pull-requests.interval.data"]="{\u0022value\u0022:\u002230000\u0022,\u0022key\u0022:\u0022dashboard.poll.pull-requests.interval\u0022,\u0022type\u0022:\u0022NUMBER\u0022}";
WRM._unparsedData["com.atlassian.bitbucket.server.config-wrm-data:dashboard.poll.pull-request-suggestions.interval.data"]="{\u0022value\u0022:\u002210000\u0022,\u0022key\u0022:\u0022dashboard.poll.pull-request-suggestions.interval\u0022,\u0022type\u0022:\u0022NUMBER\u0022}";
WRM._unparsedData["com.atlassian.bitbucket.server.feature-wrm-data:user.time.zone.onboarding.data"]="true";
WRM._unparsedData["com.atlassian.bitbucket.server.feature-wrm-data:data.center.data"]="true";
if(window.WRM._dataArrived)window.WRM._dataArrived();</script>
<link rel="stylesheet" href="/s/dc032e9ac4bb5d1355ae2e5403547a8e-CDN/1321798197/78940fd/n1cn5w/a93e8b54a53a5453c42e8c7cfb35551a/_/download/contextbatch/css/_super/batch.css" data-wrm-key="_super" data-wrm-batch-type="context" media="all">
<link rel="stylesheet" href="/s/1921e174d8ad53856b9f312a13256791-CDN/1321798197/78940fd/n1cn5w/e09bcf20c0fc47a6416af6c6ad7eacbc/_/download/contextbatch/css/bitbucket.page.dashboard,atl.general,bitbucket.internal.feature.theme,bitbucket.layout.base,zdu-banner-all,-_super/batch.css" data-wrm-key="bitbucket.page.dashboard,atl.general,bitbucket.internal.feature.theme,bitbucket.layout.base,zdu-banner-all,-_super" data-wrm-batch-type="context" media="all">
<script src="/s/eed0c00a3ff701d547fab8ae8b804bb6-CDN/1321798197/78940fd/n1cn5w/a93e8b54a53a5453c42e8c7cfb35551a/_/download/contextbatch/js/_super/batch.js?locale=en-US" data-wrm-key="_super" data-wrm-batch-type="context" data-initially-rendered=""></script>
<script src="/s/17cb3df87d2e71ff9f4c4cba3ef2d1e1-CDN/1321798197/78940fd/n1cn5w/e09bcf20c0fc47a6416af6c6ad7eacbc/_/download/contextbatch/js/bitbucket.page.dashboard,atl.general,bitbucket.internal.feature.theme,bitbucket.layout.base,zdu-banner-all,-_super/batch.js?locale=en-US" data-wrm-key="bitbucket.page.dashboard,atl.general,bitbucket.internal.feature.theme,bitbucket.layout.base,zdu-banner-all,-_super" data-wrm-batch-type="context" data-initially-rendered=""></script>
<meta name="application-name" content="Bitbucket"><link rel="shortcut icon" type="image/x-icon" href="/s/1321798197/78940fd/n1cn5w/1.0/_/download/resources/com.atlassian.bitbucket.server.bitbucket-webpack-INTERNAL:favicon/favicon.ico"><link rel="search" href="https://bitbucket.trundl.com/plugins/servlet/opensearch-descriptor" type="application/opensearchdescription+xml" title="Bitbucket code search"><style data-emotion="css"></style><style data-emotion="css" data-s=""></style></head>